-- MySQL Script generated by MySQL Workbench
-- 05/04/17 12:31:36
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`image` (
  `idimage` INT NOT NULL AUTO_INCREMENT,
  `localimage` VARCHAR(100) NOT NULL,
  `dateimage` DATETIME NULL,
  `localthumbnail` VARCHAR(100) NULL,
  `imagecol` VARCHAR(45) NULL,
  PRIMARY KEY (`idimage`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`news`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`news` (
  `idnews` INT NOT NULL AUTO_INCREMENT,
  `titlenews` VARCHAR(255) NOT NULL,
  `articlenews` LONGTEXT NOT NULL,
  `datenews` DATETIME NOT NULL,
  `mainarticle` VARCHAR(255) NOT NULL,
  `image_idimage` INT NOT NULL,
  PRIMARY KEY (`idnews`),
  INDEX `fk_news_image1_idx` (`image_idimage` ASC),
  CONSTRAINT `fk_news_image1`
    FOREIGN KEY (`image_idimage`)
    REFERENCES `mydb`.`image` (`idimage`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`videos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`videos` (
  `idvideos` INT NOT NULL AUTO_INCREMENT,
  `linkvideo` VARCHAR(100) NULL,
  `datevideo` DATETIME NULL,
  PRIMARY KEY (`idvideos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Hq`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Hq` (
  `idHq` INT NOT NULL AUTO_INCREMENT,
  `hqtitle` VARCHAR(255) NOT NULL,
  `linkhq` VARCHAR(255) NOT NULL,
  `image_idimage` INT NOT NULL,
  PRIMARY KEY (`idHq`),
  INDEX `fk_Hq_image1_idx` (`image_idimage` ASC),
  CONSTRAINT `fk_Hq_image1`
    FOREIGN KEY (`image_idimage`)
    REFERENCES `mydb`.`image` (`idimage`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
